
package net.azister.azisterweaponsedeco.init;

import net.azister.azisterweaponsedeco.block.MistBlock;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

import net.azister.azisterweaponsedeco.AzisterweaponsedecoMod;

public class AzisterweaponsedecoModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, AzisterweaponsedecoMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> AZISTER_DECO = REGISTRY.register("azister_deco", () -> CreativeModeTab.builder().title(Component.translatable("item_group.azisterweaponsedeco.azister_deco")).icon(() -> new ItemStack(AzisterweaponsedecoModBlocks.BEIRA_PEDRA.get())).displayItems((parameters, tabData) -> {
		tabData.accept(AzisterweaponsedecoModBlocks.N_GOLDEN_MARBLE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.N_GOLDEN_MARBLE_P.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.N_HELL_MARBLE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.STEPS.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.CRUSHERBLOCK.get().asItem());

		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_PEDRA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_DEEP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_DARK.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_BARRO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_TIJOLO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_QUARTZ.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_END.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_END_P.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_ANDE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_DIOR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_GRAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_DARKP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_GOLDEN_MARBLE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_N_HELL_MARBLE.get().asItem());

		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_PEDRA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_DEEP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_DARK.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_BARRO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_TIJOLO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_QUARTZ.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_END.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_END_P.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_ANDE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_DIOR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_GRAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_DARKP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_GOLDEN_MARBLE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAC_N_HELL_MARBLE.get().asItem());

		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_PEDRA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_DEEP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_DARK.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_BARRO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_TIJOLO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_QUARTZ.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_END.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_END_P.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_ANDE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_DIOR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_GRAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_DARKP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_GOLDEN_MARBLE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_N_HELL_MARBLE.get().asItem());

		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_PEDRA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_DEEP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_DARK.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_BARRO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_TIJOLO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_QUARTZ.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_END.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_END_P.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_ANDE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_DIOR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_GRAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_DARKP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_GOLDEN_MARBLE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRACF_N_HELL_MARBLE.get().asItem());

		tabData.accept(AzisterweaponsedecoModBlocks.MIST_ANDE_GMARB.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_ANDE_HMARB.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DIOR_DARK.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DIOR_GRAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DARK_GMARB.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DARK_HMARB.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DIOR_ANDE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DARK_GRAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DARK_ANDE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DIOR_GMARB.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_DIOR_HMARB.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_GMARB_HMARB.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_GRAN_ANDE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_GRAN_GMARB.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.MIST_GRAN_HMARB.get().asItem());

		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_PEDRA_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_DEEP_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_DARK_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_BARRO_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_TIJOLO_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_QUARTZ_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_END_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_END_P_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_ANDE_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_DIOR_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_GRAN_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_DARKP_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_GOLDEN_MARBLE_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_N_HELL_MARBLE_LAMP.get().asItem());

		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_T.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TBRANCO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TCINZINHA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TCINZA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TPRETO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TMARR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TVERM.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TLARAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TAMAR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TLIMA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TVERD.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TCIAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TAZULZIN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TAZUL.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TROXO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TMAGEN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_TROSA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_BRANCO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_CINZINHA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_CINZA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_PRETO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_MARR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_VERM.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_LARAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_AMAR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_LIMA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_VERD.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_CIAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_AZULZIN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_AZUL.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_ROXO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_MAGEN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALL_ROSA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_T.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TBRANCO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TCINZINHA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TCINZA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TPRETO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TMARR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TVERM.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TLARAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TAMAR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TLIMA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TVERD.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TCIAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TAZULZIN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TAZUL.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TROXO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TMAGEN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_TROSA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_BRANCO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_CINZINHA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_CINZA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_PRETO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_MARR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_VERM.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_LARAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_AMAR.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_LIMA.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_VERD.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_CIAN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_AZULZIN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_AZUL.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_ROXO.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_MAGEN.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.DRYWALLC_ROSA.get().asItem());

		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBRE.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBRE1.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBRE2.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBRE3.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBREC.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBREC1.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBREC2.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBREC3.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBRE_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBRE1_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBRE2_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBRE3_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBREC_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBREC1_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBREC2_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRA_COBREC3_LAMP.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_PRISM.get().asItem());
		tabData.accept(AzisterweaponsedecoModBlocks.BEIRAF_DPRISM.get().asItem());
	}).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> AZISTER_WEAPONS = REGISTRY.register("azister_weapons", () -> CreativeModeTab.builder().title(Component.translatable("item_group.azisterweaponsedeco.azister_weapons")).icon(() -> new ItemStack(AzisterweaponsedecoModItems.TWILIGHT_SPIKE_SWORD.get())).displayItems((parameters, tabData) -> {
		tabData.accept(AzisterweaponsedecoModItems.DEEPSLATE_SHARD.get());
		tabData.accept(AzisterweaponsedecoModItems.STAR.get());
		tabData.accept(AzisterweaponsedecoModItems.ESENCIA_MORTAL.get());
		tabData.accept(AzisterweaponsedecoModItems.AZISTER_DREAM.get());
		tabData.accept(AzisterweaponsedecoModItems.REF_IRON_SWORD.get());
		tabData.accept(AzisterweaponsedecoModItems.TWILIGHT_SPIKE_SWORD.get());
		tabData.accept(AzisterweaponsedecoModItems.WINNERAXE.get());
	}).build());
}
