package net.azister.azisterweaponsedeco.init;
import java.util.function.Supplier;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public class AzisterweaponsedecoModItems
/*     */ {
/*  21 */   public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems("azisterweaponsedeco");
/*  22 */   public static final DeferredItem<Item> AZISTER_DREAM = REGISTRY.register("azister_dream", net.azister.azisterweaponsedeco.item.AzisterDreamItem::new);
/*  23 */   public static final DeferredItem<Item> BEIRA = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA);
/*  24 */   public static final DeferredItem<Item> BEIRAC = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC);
/*  25 */   public static final DeferredItem<Item> BEIRACF_ANDE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_ANDE);
/*  26 */   public static final DeferredItem<Item> BEIRACF_BARRO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_BARRO);
/*  27 */   public static final DeferredItem<Item> BEIRACF_COBRE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_COBRE);
/*  28 */   public static final DeferredItem<Item> BEIRACF_COBRE1 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_COBRE1);
/*  29 */   public static final DeferredItem<Item> BEIRACF_COBRE2 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_COBRE2);
/*  30 */   public static final DeferredItem<Item> BEIRACF_COBRE3 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_COBRE3);
/*  31 */   public static final DeferredItem<Item> BEIRACF_COBREC = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_COBREC);
/*  32 */   public static final DeferredItem<Item> BEIRACF_COBREC1 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_COBREC1);
/*  33 */   public static final DeferredItem<Item> BEIRACF_COBREC2 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_COBREC2);
/*  34 */   public static final DeferredItem<Item> BEIRACF_COBREC3 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_COBREC3);
/*  35 */   public static final DeferredItem<Item> BEIRACF_DARK = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_DARK);
/*  36 */   public static final DeferredItem<Item> BEIRACF_DARKP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_DARKP);
/*  37 */   public static final DeferredItem<Item> BEIRACF_DEEP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_DEEP);
/*  38 */   public static final DeferredItem<Item> BEIRACF_DIOR = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_DIOR);
/*  39 */   public static final DeferredItem<Item> BEIRACF_END = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_END);
/*  40 */   public static final DeferredItem<Item> BEIRACF_END_P = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_END_P);
/*  41 */   public static final DeferredItem<Item> BEIRACF_GOLDEN_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_GOLDEN_MARBLE);
/*  42 */   public static final DeferredItem<Item> BEIRACF_GRAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_GRAN);
/*  43 */   public static final DeferredItem<Item> BEIRACF_N_HELL_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_N_HELL_MARBLE);
/*  44 */   public static final DeferredItem<Item> BEIRACF_PEDRA = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_PEDRA);
/*  45 */   public static final DeferredItem<Item> BEIRACF_QUARTZ = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_QUARTZ);
/*  46 */   public static final DeferredItem<Item> BEIRACF_TIJOLO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_TIJOLO);
/*  47 */   public static final DeferredItem<Item> BEIRACF_TUFO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_TUFO);
/*  48 */   public static final DeferredItem<Item> BEIRACF_PRISM = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_PRISM);
/*  49 */   public static final DeferredItem<Item> BEIRACF_DPRISM = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRACF_DPRISM);
/*  50 */   public static final DeferredItem<Item> BEIRAC_ANDE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_ANDE);
/*  51 */   public static final DeferredItem<Item> BEIRAC_BARRO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_BARRO);
/*  52 */   public static final DeferredItem<Item> BEIRAC_COBRE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_COBRE);
/*  53 */   public static final DeferredItem<Item> BEIRAC_COBRE1 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_COBRE1);
/*  54 */   public static final DeferredItem<Item> BEIRAC_COBRE2 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_COBRE2);
/*  55 */   public static final DeferredItem<Item> BEIRAC_COBRE3 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_COBRE3);
/*  56 */   public static final DeferredItem<Item> BEIRAC_COBREC = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_COBREC);
/*  57 */   public static final DeferredItem<Item> BEIRAC_COBREC1 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_COBREC1);
/*  58 */   public static final DeferredItem<Item> BEIRAC_COBREC2 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_COBREC2);
/*  59 */   public static final DeferredItem<Item> BEIRAC_COBREC3 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_COBREC3);
/*  60 */   public static final DeferredItem<Item> BEIRAC_DARK = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_DARK);
/*  61 */   public static final DeferredItem<Item> BEIRAC_DARKP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_DARKP);
/*  62 */   public static final DeferredItem<Item> BEIRAC_DEEP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_DEEP);
/*  63 */   public static final DeferredItem<Item> BEIRAC_DIOR = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_DIOR);
/*  64 */   public static final DeferredItem<Item> BEIRAC_END = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_END);
/*  65 */   public static final DeferredItem<Item> BEIRAC_END_P = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_END_P);
/*  66 */   public static final DeferredItem<Item> BEIRAC_GOLDEN_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_GOLDEN_MARBLE);
/*  67 */   public static final DeferredItem<Item> BEIRAC_GRAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_GRAN);
/*  68 */   public static final DeferredItem<Item> BEIRAC_N_HELL_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_N_HELL_MARBLE);
/*  69 */   public static final DeferredItem<Item> BEIRAC_PEDRA = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_PEDRA);
/*  70 */   public static final DeferredItem<Item> BEIRAC_DPRISM = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_DPRISM);
/*  71 */   public static final DeferredItem<Item> BEIRAC_QUARTZ = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_QUARTZ);
/*  72 */   public static final DeferredItem<Item> BEIRAC_TIJOLO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_TIJOLO);
/*  73 */   public static final DeferredItem<Item> BEIRAC_PRISM = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_PRISM);
/*  74 */   public static final DeferredItem<Item> BEIRAC_TUFO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAC_TUFO);
/*  75 */   public static final DeferredItem<Item> BEIRAF_ANDE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_ANDE);
/*  76 */   public static final DeferredItem<Item> BEIRAF_BARRO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_BARRO);
/*  77 */   public static final DeferredItem<Item> BEIRAF_COBRE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_COBRE);
/*  78 */   public static final DeferredItem<Item> BEIRAF_COBRE1 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_COBRE1);
/*  79 */   public static final DeferredItem<Item> BEIRAF_COBRE2 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_COBRE2);
/*  80 */   public static final DeferredItem<Item> BEIRAF_COBRE3 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_COBRE3);
/*  81 */   public static final DeferredItem<Item> BEIRAF_COBREC = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_COBREC);
/*  82 */   public static final DeferredItem<Item> BEIRAF_COBREC1 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_COBREC1);
/*  83 */   public static final DeferredItem<Item> BEIRAF_COBREC2 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_COBREC2);
/*  84 */   public static final DeferredItem<Item> BEIRAF_COBREC3 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_COBREC3);
/*  85 */   public static final DeferredItem<Item> BEIRAF_DARK = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_DARK);
/*  86 */   public static final DeferredItem<Item> BEIRAF_DARKP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_DARKP);
/*  87 */   public static final DeferredItem<Item> BEIRAF_DEEP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_DEEP);
/*  88 */   public static final DeferredItem<Item> BEIRAF_DIOR = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_DIOR);
/*  89 */   public static final DeferredItem<Item> BEIRAF_END = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_END);
/*  90 */   public static final DeferredItem<Item> BEIRAF_END_P = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_END_P);
/*  91 */   public static final DeferredItem<Item> BEIRAF_GOLDEN_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_GOLDEN_MARBLE);
/*  92 */   public static final DeferredItem<Item> BEIRAF_GRAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_GRAN);
/*  93 */   public static final DeferredItem<Item> BEIRAF_N_HELL_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_N_HELL_MARBLE);
/*  94 */   public static final DeferredItem<Item> BEIRAF_PEDRA = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_PEDRA);
/*  95 */   public static final DeferredItem<Item> BEIRAF_QUARTZ = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_QUARTZ);
/*  96 */   public static final DeferredItem<Item> BEIRAF_TIJOLO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_TIJOLO);
/*  97 */   public static final DeferredItem<Item> BEIRAF_TUFO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_TUFO);
/*  98 */   public static final DeferredItem<Item> BEIRAF_PRISM = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_PRISM);
/*  99 */   public static final DeferredItem<Item> BEIRAF_DPRISM = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRAF_DPRISM);
/* 100 */   public static final DeferredItem<Item> BEIRA_ANDE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_ANDE);
/* 101 */   public static final DeferredItem<Item> BEIRA_ANDE_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_ANDE_LAMP);
/* 102 */   public static final DeferredItem<Item> BEIRA_BARRO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_BARRO);
/* 103 */   public static final DeferredItem<Item> BEIRA_BARRO_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_BARRO_LAMP);
/* 104 */   public static final DeferredItem<Item> BEIRA_COBRE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBRE);
/* 105 */   public static final DeferredItem<Item> BEIRA_COBRE1 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBRE1);
/* 106 */   public static final DeferredItem<Item> BEIRA_COBRE2 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBRE2);
/* 107 */   public static final DeferredItem<Item> BEIRA_COBRE3 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBRE3);
/* 108 */   public static final DeferredItem<Item> BEIRA_COBREC = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBREC);
/* 109 */   public static final DeferredItem<Item> BEIRA_COBREC1 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBREC1);
/* 110 */   public static final DeferredItem<Item> BEIRA_COBREC2 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBREC2);
/* 111 */   public static final DeferredItem<Item> BEIRA_COBREC3 = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBREC3);
/* 112 */   public static final DeferredItem<Item> BEIRA_COBRE_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBRE_LAMP);
/* 113 */   public static final DeferredItem<Item> BEIRA_COBRE1_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBRE1_LAMP);
/* 114 */   public static final DeferredItem<Item> BEIRA_COBRE2_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBRE2_LAMP);
/* 115 */   public static final DeferredItem<Item> BEIRA_COBRE3_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBRE3_LAMP);
/* 116 */   public static final DeferredItem<Item> BEIRA_COBREC_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBREC_LAMP);
/* 117 */   public static final DeferredItem<Item> BEIRA_COBREC1_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBREC1_LAMP);
/* 118 */   public static final DeferredItem<Item> BEIRA_COBREC2_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBREC2_LAMP);
/* 119 */   public static final DeferredItem<Item> BEIRA_COBREC3_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_COBREC3_LAMP);
/* 120 */   public static final DeferredItem<Item> BEIRA_DARK = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DARK);
/* 121 */   public static final DeferredItem<Item> BEIRA_DARKP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DARKP);
/* 122 */   public static final DeferredItem<Item> BEIRA_DARK_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DARK_LAMP);
/* 123 */   public static final DeferredItem<Item> BEIRA_DARKP_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DARKP_LAMP);
/* 124 */   public static final DeferredItem<Item> BEIRA_DEEP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DEEP);
/* 125 */   public static final DeferredItem<Item> BEIRA_DEEP_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DEEP_LAMP);
/* 126 */   public static final DeferredItem<Item> BEIRA_DIOR = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DIOR);
/* 127 */   public static final DeferredItem<Item> BEIRA_DIOR_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DIOR_LAMP);
/* 128 */   public static final DeferredItem<Item> BEIRA_END = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_END);
/* 129 */   public static final DeferredItem<Item> BEIRA_END_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_END_LAMP);
/* 130 */   public static final DeferredItem<Item> BEIRA_END_P = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_END_P);
/* 131 */   public static final DeferredItem<Item> BEIRA_END_P_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_END_P_LAMP);
/* 132 */   public static final DeferredItem<Item> BEIRA_GOLDEN_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_GOLDEN_MARBLE);
/* 133 */   public static final DeferredItem<Item> BEIRA_GOLDEN_MARBLE_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_GOLDEN_MARBLE_LAMP);
/* 134 */   public static final DeferredItem<Item> BEIRA_GRAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_GRAN);
/* 135 */   public static final DeferredItem<Item> BEIRA_GRAN_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_GRAN_LAMP);
/* 136 */   public static final DeferredItem<Item> BEIRA_N_HELL_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_N_HELL_MARBLE);
/* 137 */   public static final DeferredItem<Item> BEIRA_N_HELL_MARBLE_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_N_HELL_MARBLE_LAMP);
/* 138 */   public static final DeferredItem<Item> BEIRA_PEDRA = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_PEDRA);
/* 139 */   public static final DeferredItem<Item> BEIRA_PEDRA_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_PEDRA_LAMP);
/* 140 */   public static final DeferredItem<Item> BEIRA_QUARTZ = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_QUARTZ);
/* 141 */   public static final DeferredItem<Item> BEIRA_QUARTZ_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_QUARTZ_LAMP);
/* 142 */   public static final DeferredItem<Item> BEIRA_TIJOLO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_TIJOLO);
/* 143 */   public static final DeferredItem<Item> BEIRA_TIJOLO_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_TIJOLO_LAMP);
/* 144 */   public static final DeferredItem<Item> BEIRA_TUFO = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_TUFO);
/* 145 */   public static final DeferredItem<Item> BEIRA_TUFO_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_TUFO_LAMP);
/* 146 */   public static final DeferredItem<Item> BEIRA_PRISM = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_PRISM);
/* 147 */   public static final DeferredItem<Item> BEIRA_PRISM_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_PRISM_LAMP);
/* 148 */   public static final DeferredItem<Item> BEIRA_DPRISM = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DPRISM);
/* 149 */   public static final DeferredItem<Item> BEIRA_DPRISM_LAMP = block((DeferredHolder)AzisterweaponsedecoModBlocks.BEIRA_DPRISM_LAMP);
/* 150 */   public static final DeferredItem<Item> CRUSHERBLOCK = block((DeferredHolder)AzisterweaponsedecoModBlocks.CRUSHERBLOCK);
/* 151 */   public static final DeferredItem<Item> DEEPSLATE_SHARD = REGISTRY.register("deepslate_shard", net.azister.azisterweaponsedeco.item.DeepslateShardItem::new);
/* 152 */   public static final DeferredItem<Item> DRYWALLC_AMAR = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_AMAR);
/* 153 */   public static final DeferredItem<Item> DRYWALLC_AZUL = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_AZUL);
/* 154 */   public static final DeferredItem<Item> DRYWALLC_AZULZIN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_AZULZIN);
/* 155 */   public static final DeferredItem<Item> DRYWALLC_BRANCO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_BRANCO);
/* 156 */   public static final DeferredItem<Item> DRYWALLC_CIAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_CIAN);
/* 157 */   public static final DeferredItem<Item> DRYWALLC_CINZA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_CINZA);
/* 158 */   public static final DeferredItem<Item> DRYWALLC_CINZINHA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_CINZINHA);
/* 159 */   public static final DeferredItem<Item> DRYWALLC_LARAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_LARAN);
/* 160 */   public static final DeferredItem<Item> DRYWALLC_LIMA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_LIMA);
/* 161 */   public static final DeferredItem<Item> DRYWALLC_MAGEN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_MAGEN);
/* 162 */   public static final DeferredItem<Item> DRYWALLC_MARR = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_MARR);
/* 163 */   public static final DeferredItem<Item> DRYWALLC_PRETO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_PRETO);
/* 164 */   public static final DeferredItem<Item> DRYWALLC_ROSA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_ROSA);
/* 165 */   public static final DeferredItem<Item> DRYWALLC_ROXO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_ROXO);
/* 166 */   public static final DeferredItem<Item> DRYWALLC_T = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_T);
/* 167 */   public static final DeferredItem<Item> DRYWALLC_TAMAR = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TAMAR);
/* 168 */   public static final DeferredItem<Item> DRYWALLC_TAZUL = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TAZUL);
/* 169 */   public static final DeferredItem<Item> DRYWALLC_TAZULZIN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TAZULZIN);
/* 170 */   public static final DeferredItem<Item> DRYWALLC_TBRANCO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TBRANCO);
/* 171 */   public static final DeferredItem<Item> DRYWALLC_TCIAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TCIAN);
/* 172 */   public static final DeferredItem<Item> DRYWALLC_TCINZA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TCINZA);
/* 173 */   public static final DeferredItem<Item> DRYWALLC_TCINZINHA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TCINZINHA);
/* 174 */   public static final DeferredItem<Item> DRYWALLC_TLARAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TLARAN);
/* 175 */   public static final DeferredItem<Item> DRYWALLC_TLIMA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TLIMA);
/* 176 */   public static final DeferredItem<Item> DRYWALLC_TMAGEN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TMAGEN);
/* 177 */   public static final DeferredItem<Item> DRYWALLC_TMARR = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TMARR);
/* 178 */   public static final DeferredItem<Item> DRYWALLC_TPRETO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TPRETO);
/* 179 */   public static final DeferredItem<Item> DRYWALLC_TROSA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TROSA);
/* 180 */   public static final DeferredItem<Item> DRYWALLC_TROXO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TROXO);
/* 181 */   public static final DeferredItem<Item> DRYWALLC_TVERD = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TVERD);
/* 182 */   public static final DeferredItem<Item> DRYWALLC_TVERM = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_TVERM);
/* 183 */   public static final DeferredItem<Item> DRYWALLC_VERD = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_VERD);
/* 184 */   public static final DeferredItem<Item> DRYWALLC_VERM = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALLC_VERM);
/* 185 */   public static final DeferredItem<Item> DRYWALL_AMAR = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_AMAR);
/* 186 */   public static final DeferredItem<Item> DRYWALL_AZUL = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_AZUL);
/* 187 */   public static final DeferredItem<Item> DRYWALL_AZULZIN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_AZULZIN);
/* 188 */   public static final DeferredItem<Item> DRYWALL_BRANCO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_BRANCO);
/* 189 */   public static final DeferredItem<Item> DRYWALL_CIAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_CIAN);
/* 190 */   public static final DeferredItem<Item> DRYWALL_CINZA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_CINZA);
/* 191 */   public static final DeferredItem<Item> DRYWALL_CINZINHA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_CINZINHA);
/* 192 */   public static final DeferredItem<Item> DRYWALL_LARAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_LARAN);
/* 193 */   public static final DeferredItem<Item> DRYWALL_LIMA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_LIMA);
/* 194 */   public static final DeferredItem<Item> DRYWALL_MAGEN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_MAGEN);
/* 195 */   public static final DeferredItem<Item> DRYWALL_MARR = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_MARR);
/* 196 */   public static final DeferredItem<Item> DRYWALL_PRETO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_PRETO);
/* 197 */   public static final DeferredItem<Item> DRYWALL_ROSA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_ROSA);
/* 198 */   public static final DeferredItem<Item> DRYWALL_ROXO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_ROXO);
/* 199 */   public static final DeferredItem<Item> DRYWALL_T = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_T);
/* 200 */   public static final DeferredItem<Item> DRYWALL_TAMAR = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TAMAR);
/* 201 */   public static final DeferredItem<Item> DRYWALL_TAZUL = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TAZUL);
/* 202 */   public static final DeferredItem<Item> DRYWALL_TAZULZIN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TAZULZIN);
/* 203 */   public static final DeferredItem<Item> DRYWALL_TBRANCO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TBRANCO);
/* 204 */   public static final DeferredItem<Item> DRYWALL_TCIAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TCIAN);
/* 205 */   public static final DeferredItem<Item> DRYWALL_TCINZA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TCINZA);
/* 206 */   public static final DeferredItem<Item> DRYWALL_TCINZINHA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TCINZINHA);
/* 207 */   public static final DeferredItem<Item> DRYWALL_TLARAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TLARAN);
/* 208 */   public static final DeferredItem<Item> DRYWALL_TLIMA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TLIMA);
/* 209 */   public static final DeferredItem<Item> DRYWALL_TMAGEN = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TMAGEN);
/* 210 */   public static final DeferredItem<Item> DRYWALL_TMARR = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TMARR);
/* 211 */   public static final DeferredItem<Item> DRYWALL_TPRETO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TPRETO);
/* 212 */   public static final DeferredItem<Item> DRYWALL_TROSA = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TROSA);
/* 213 */   public static final DeferredItem<Item> DRYWALL_TROXO = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TROXO);
/* 214 */   public static final DeferredItem<Item> DRYWALL_TVERD = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TVERD);
/* 215 */   public static final DeferredItem<Item> DRYWALL_TVERM = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_TVERM);
/* 216 */   public static final DeferredItem<Item> DRYWALL_VERD = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_VERD);
/* 217 */   public static final DeferredItem<Item> DRYWALL_VERM = block((DeferredHolder)AzisterweaponsedecoModBlocks.DRYWALL_VERM);
/* 218 */   public static final DeferredItem<Item> ESENCIA_MORTAL = REGISTRY.register("esencia_mortal", net.azister.azisterweaponsedeco.item.EsenciaMortalItem::new);
/* 219 */   public static final DeferredItem<Item> MIST = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST);
/* 220 */   public static final DeferredItem<Item> MIST_ANDE_GMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_ANDE_GMARB);
/* 221 */   public static final DeferredItem<Item> MIST_ANDE_HMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_ANDE_HMARB);
/* 222 */   public static final DeferredItem<Item> MIST_DARK_ANDE = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DARK_ANDE);
/* 223 */   public static final DeferredItem<Item> MIST_DARK_GRAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DARK_GRAN);
/* 224 */   public static final DeferredItem<Item> MIST_DARK_GMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DARK_GMARB);
/* 225 */   public static final DeferredItem<Item> MIST_DARK_HMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DARK_HMARB);
/* 226 */   public static final DeferredItem<Item> MIST_DIOR_ANDE = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DIOR_ANDE);
/* 227 */   public static final DeferredItem<Item> MIST_DIOR_DARK = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DIOR_DARK);
/* 228 */   public static final DeferredItem<Item> MIST_DIOR_GRAN = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DIOR_GRAN);
/* 229 */   public static final DeferredItem<Item> MIST_DIOR_GMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DIOR_GMARB);
/* 230 */   public static final DeferredItem<Item> MIST_DIOR_HMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_DIOR_HMARB);
/* 231 */   public static final DeferredItem<Item> MIST_GMARB_HMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_GMARB_HMARB);
/* 232 */   public static final DeferredItem<Item> MIST_GRAN_ANDE = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_GRAN_ANDE);
/* 233 */   public static final DeferredItem<Item> MIST_GRAN_GMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_GRAN_GMARB);
/* 234 */   public static final DeferredItem<Item> MIST_GRAN_HMARB = block((DeferredHolder)AzisterweaponsedecoModBlocks.MIST_GRAN_HMARB);
/* 235 */   public static final DeferredItem<Item> N_GOLDEN_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.N_GOLDEN_MARBLE);
/* 236 */   public static final DeferredItem<Item> N_GOLDEN_MARBLE_P = block((DeferredHolder)AzisterweaponsedecoModBlocks.N_GOLDEN_MARBLE_P);
/* 237 */   public static final DeferredItem<Item> N_HELL_MARBLE = block((DeferredHolder)AzisterweaponsedecoModBlocks.N_HELL_MARBLE);
/* 238 */   public static final DeferredItem<Item> OXIDIZED_COPPER_SWORD = REGISTRY.register("oxidized_copper_sword", net.azister.azisterweaponsedeco.item.OxiCopperSwordItem::new);
/* 239 */   public static final DeferredItem<Item> WEATHERED_COPPER_SWORD = REGISTRY.register("weathered_copper_sword", net.azister.azisterweaponsedeco.item.WeatherCopperSwordItem::new);
/* 240 */   public static final DeferredItem<Item> EXPOSED_COPPER_SWORD = REGISTRY.register("exposed_copper_sword", net.azister.azisterweaponsedeco.item.ExpoCopperSwordItem::new);
/* 241 */   public static final DeferredItem<Item> COPPER_SWORD = REGISTRY.register("copper_sword", net.azister.azisterweaponsedeco.item.CopperSwordItem::new);
/* 242 */   public static final DeferredItem<Item> REF_COPPER_SWORD = REGISTRY.register("ref_copper_sword", net.azister.azisterweaponsedeco.item.RefCopperSwordItem::new);
/* 243 */   public static final DeferredItem<Item> REF_IRON_SWORD = REGISTRY.register("ref_iron_sword", net.azister.azisterweaponsedeco.item.RefIronSwordItem::new);
/* 244 */   public static final DeferredItem<Item> STAR = REGISTRY.register("star", net.azister.azisterweaponsedeco.item.StarItem::new);
/* 245 */   public static final DeferredItem<Item> STEPS = block((DeferredHolder)AzisterweaponsedecoModBlocks.STEPS);
/* 246 */   public static final DeferredItem<Item> TWILIGHT_SPIKE_SWORD = REGISTRY.register("twilight_spike_sword", net.azister.azisterweaponsedeco.item.TwilightSpikeSwordItem::new);
/* 247 */   public static final DeferredItem<Item> WINNERAXE = REGISTRY.register("winneraxe", net.azister.azisterweaponsedeco.item.WinneraxeItem::new);
/*     */
/*     */ 
/*     */   
/*     */   private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
/* 252 */     return REGISTRY.register(block.getId().getPath(), () -> new BlockItem((Block)block.get(), new Item.Properties()));
/*     */   }
/*     */ }
