
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.azister.azisterweaponsedeco.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.azister.azisterweaponsedeco.block.StepsBlock;
import net.azister.azisterweaponsedeco.block.NHellMarbleBlock;
import net.azister.azisterweaponsedeco.block.NGoldenMarbleBlock;
import net.azister.azisterweaponsedeco.block.MistBlock;
import net.azister.azisterweaponsedeco.block.CrusherblockBlock;
import net.azister.azisterweaponsedeco.block.BeiracBlock;
import net.azister.azisterweaponsedeco.block.BeiraPedraLampBlock;
import net.azister.azisterweaponsedeco.block.BeiraBlock;
import net.azister.azisterweaponsedeco.AzisterweaponsedecoMod;

public class AzisterweaponsedecoModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(AzisterweaponsedecoMod.MODID);
	public static final DeferredBlock<Block> BEIRA_PEDRA = REGISTRY.register("beira_pedra", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_DEEP = REGISTRY.register("beira_deep", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_DARK = REGISTRY.register("beira_dark", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_BARRO = REGISTRY.register("beira_barro", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_QUARTZ = REGISTRY.register("beira_quartz", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_END = REGISTRY.register("beira_end", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_END_P = REGISTRY.register("beira_end_p", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_ANDE = REGISTRY.register("beira_ande", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_DIOR = REGISTRY.register("beira_dior", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_GRAN = REGISTRY.register("beira_gran", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_PEDRA = REGISTRY.register("beiraf_pedra", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_DEEP = REGISTRY.register("beiraf_deep", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_DARK = REGISTRY.register("beiraf_dark", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_BARRO = REGISTRY.register("beiraf_barro", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_QUARTZ = REGISTRY.register("beiraf_quartz", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_END = REGISTRY.register("beiraf_end", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_END_P = REGISTRY.register("beiraf_end_p", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_ANDE = REGISTRY.register("beiraf_ande", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_DIOR = REGISTRY.register("beiraf_dior", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_GRAN = REGISTRY.register("beiraf_gran", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAC_PEDRA = REGISTRY.register("beirac_pedra", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_DEEP = REGISTRY.register("beirac_deep", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_DARK = REGISTRY.register("beirac_dark", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_BARRO = REGISTRY.register("beirac_barro", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_QUARTZ = REGISTRY.register("beirac_quartz", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_END = REGISTRY.register("beirac_end", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_END_P = REGISTRY.register("beirac_end_p", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_ANDE = REGISTRY.register("beirac_ande", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_DIOR = REGISTRY.register("beirac_dior", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRAC_GRAN = REGISTRY.register("beirac_gran", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_PEDRA = REGISTRY.register("beiracf_pedra", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_DEEP = REGISTRY.register("beiracf_deep", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_DARK = REGISTRY.register("beiracf_dark", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_BARRO = REGISTRY.register("beiracf_barro", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_QUARTZ = REGISTRY.register("beiracf_quartz", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_END = REGISTRY.register("beiracf_end", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_END_P = REGISTRY.register("beiracf_end_p", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_ANDE = REGISTRY.register("beiracf_ande", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_DIOR = REGISTRY.register("beiracf_dior", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_GRAN = REGISTRY.register("beiracf_gran", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALL_T = REGISTRY.register("drywall_t", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA = REGISTRY.register("beira", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAC = REGISTRY.register("beirac", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TBRANCO = REGISTRY.register("drywall_tbranco", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TCINZINHA = REGISTRY.register("drywall_tcinzinha", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TCINZA = REGISTRY.register("drywall_tcinza", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TPRETO = REGISTRY.register("drywall_tpreto", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TMARR = REGISTRY.register("drywall_tmarr", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TVERM = REGISTRY.register("drywall_tverm", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TLARAN = REGISTRY.register("drywall_tlaran", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TAMAR = REGISTRY.register("drywall_tamar", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TLIMA = REGISTRY.register("drywall_tlima", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TVERD = REGISTRY.register("drywall_tverd", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TCIAN = REGISTRY.register("drywall_tcian", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TAZULZIN = REGISTRY.register("drywall_tazulzin", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TAZUL = REGISTRY.register("drywall_tazul", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TROXO = REGISTRY.register("drywall_troxo", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TMAGEN = REGISTRY.register("drywall_tmagen", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_TROSA = REGISTRY.register("drywall_trosa", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRA_DARKP = REGISTRY.register("beira_darkp", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_DARKP = REGISTRY.register("beiraf_darkp", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAC_DARKP = REGISTRY.register("beirac_darkp", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_DARKP = REGISTRY.register("beiracf_darkp", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRA_TIJOLO = REGISTRY.register("beira_tijolo", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAF_TIJOLO = REGISTRY.register("beiraf_tijolo", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAC_TIJOLO = REGISTRY.register("beirac_tijolo", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_TIJOLO = REGISTRY.register("beiracf_tijolo", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALL_BRANCO = REGISTRY.register("drywall_branco", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_CINZINHA = REGISTRY.register("drywall_cinzinha", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_CINZA = REGISTRY.register("drywall_cinza", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_PRETO = REGISTRY.register("drywall_preto", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_MARR = REGISTRY.register("drywall_marr", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_VERM = REGISTRY.register("drywall_verm", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_LARAN = REGISTRY.register("drywall_laran", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_AMAR = REGISTRY.register("drywall_amar", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_LIMA = REGISTRY.register("drywall_lima", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_VERD = REGISTRY.register("drywall_verd", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_CIAN = REGISTRY.register("drywall_cian", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_AZULZIN = REGISTRY.register("drywall_azulzin", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_AZUL = REGISTRY.register("drywall_azul", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_ROXO = REGISTRY.register("drywall_roxo", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_MAGEN = REGISTRY.register("drywall_magen", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALL_ROSA = REGISTRY.register("drywall_rosa", BeiraBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_T = REGISTRY.register("drywallc_t", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TBRANCO = REGISTRY.register("drywallc_tbranco", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TCINZINHA = REGISTRY.register("drywallc_tcinzinha", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TCINZA = REGISTRY.register("drywallc_tcinza", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TPRETO = REGISTRY.register("drywallc_tpreto", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TMARR = REGISTRY.register("drywallc_tmarr", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TVERM = REGISTRY.register("drywallc_tverm", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TLARAN = REGISTRY.register("drywallc_tlaran", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TAMAR = REGISTRY.register("drywallc_tamar", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TLIMA = REGISTRY.register("drywallc_tlima", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TVERD = REGISTRY.register("drywallc_tverd", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TCIAN = REGISTRY.register("drywallc_tcian", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TAZULZIN = REGISTRY.register("drywallc_tazulzin", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TAZUL = REGISTRY.register("drywallc_tazul", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TROXO = REGISTRY.register("drywallc_troxo", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TMAGEN = REGISTRY.register("drywallc_tmagen", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_TROSA = REGISTRY.register("drywallc_trosa", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_BRANCO = REGISTRY.register("drywallc_branco", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_CINZINHA = REGISTRY.register("drywallc_cinzinha", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_CINZA = REGISTRY.register("drywallc_cinza", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_PRETO = REGISTRY.register("drywallc_preto", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_MARR = REGISTRY.register("drywallc_marr", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_VERM = REGISTRY.register("drywallc_verm", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_LARAN = REGISTRY.register("drywallc_laran", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_AMAR = REGISTRY.register("drywallc_amar", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_LIMA = REGISTRY.register("drywallc_lima", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_VERD = REGISTRY.register("drywallc_verd", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_CIAN = REGISTRY.register("drywallc_cian", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_AZULZIN = REGISTRY.register("drywallc_azulzin", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_AZUL = REGISTRY.register("drywallc_azul", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_ROXO = REGISTRY.register("drywallc_roxo", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_MAGEN = REGISTRY.register("drywallc_magen", BeiracBlock::new);
	public static final DeferredBlock<Block> DRYWALLC_ROSA = REGISTRY.register("drywallc_rosa", BeiracBlock::new);
	public static final DeferredBlock<Block> MIST = REGISTRY.register("mist", MistBlock::new);
	public static final DeferredBlock<Block> MIST_DIOR_DARK = REGISTRY.register("mist_dior_dark", MistBlock::new);
	public static final DeferredBlock<Block> MIST_DIOR_GRAN = REGISTRY.register("mist_dior_gran", MistBlock::new);
	public static final DeferredBlock<Block> MIST_DIOR_ANDE = REGISTRY.register("mist_dior_ande", MistBlock::new);
	public static final DeferredBlock<Block> MIST_DARK_GRAN = REGISTRY.register("mist_dark_gran", MistBlock::new);
	public static final DeferredBlock<Block> MIST_DARK_ANDE = REGISTRY.register("mist_dark_ande", MistBlock::new);
	public static final DeferredBlock<Block> MIST_GRAN_ANDE = REGISTRY.register("mist_gran_ande", MistBlock::new);
	public static final DeferredBlock<Block> STEPS = REGISTRY.register("steps", StepsBlock::new);
	public static final DeferredBlock<Block> N_GOLDEN_MARBLE = REGISTRY.register("n_golden_marble", NGoldenMarbleBlock::new);
	public static final DeferredBlock<Block> N_GOLDEN_MARBLE_P = REGISTRY.register("n_golden_marble_p", NGoldenMarbleBlock::new);
	public static final DeferredBlock<Block> CRUSHERBLOCK = REGISTRY.register("crusherblock", CrusherblockBlock::new);
	public static final DeferredBlock<Block> BEIRA_GOLDEN_MARBLE = REGISTRY.register("beira_golden_marble", BeiraBlock::new);
	public static final DeferredBlock<Block> N_HELL_MARBLE = REGISTRY.register("n_hell_marble", NHellMarbleBlock::new);
	public static final DeferredBlock<Block> BEIRAF_GOLDEN_MARBLE = REGISTRY.register("beiraf_golden_marble", BeiraBlock::new);
	public static final DeferredBlock<Block> BEIRAC_GOLDEN_MARBLE = REGISTRY.register("beirac_golden_marble", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRACF_GOLDEN_MARBLE = REGISTRY.register("beiracf_golden_marble", BeiracBlock::new);
	public static final DeferredBlock<Block> BEIRA_PEDRA_LAMP = REGISTRY.register("beira_pedra_lamp", BeiraPedraLampBlock::new);
	public static final DeferredBlock<Block> BEIRA_DEEP_LAMP = REGISTRY.register("beira_deep_lamp", BeiraPedraLampBlock::new);
	public static final DeferredBlock<Block> BEIRA_DARK_LAMP = REGISTRY.register("beira_dark_lamp", BeiraPedraLampBlock::new);
	public static final DeferredBlock<Block> BEIRA_BARRO_LAMP = REGISTRY.register("beira_barro_lamp", BeiraPedraLampBlock::new);
	public static final DeferredBlock<Block> BEIRA_QUARTZ_LAMP = REGISTRY.register("beira_quartz_lamp", BeiraPedraLampBlock::new);
	public static final DeferredBlock<Block> BEIRA_END_LAMP = REGISTRY.register("beira_end_lamp", BeiraPedraLampBlock::new);
	public static final DeferredBlock<Block> BEIRA_END_P_LAMP = REGISTRY.register("beira_end_p_lamp", BeiraPedraLampBlock::new);
	public static final DeferredBlock<Block> BEIRA_ANDE_LAMP = REGISTRY.register("beira_ande_lamp", BeiraPedraLampBlock::new);
}
